"""create scans table

Revision ID: 3d7996cf0e45
Revises: ce7fe908f482
Create Date: 2026-09-02 20:02:51.151791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d7996cf0e45'
down_revision: Union[str, Sequence[str], None] = 'ce7fe908f482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scans',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('local_id', sa.Integer(), nullable=False),
                    sa.Column('plant_name', sa.String(
                        length=100), nullable=False),
                    sa.Column('disease_name', sa.String(
                        length=150), nullable=False),
                    sa.Column('confidence', sa.Integer(), nullable=False),
                    sa.Column('symptoms', sa.Text(), nullable=False),
                    sa.Column('treatment_local', sa.Text(), nullable=False),
                    sa.Column('treatment_chemical', sa.Text(), nullable=False),
                    sa.Column('timestamp', sa.Integer(), nullable=False),
                    sa.Column('latitude', sa.Float(), nullable=True),
                    sa.Column('longitude', sa.Float(), nullable=True),
                    sa.Column('received_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
                    sa.Column('srid', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('auth_name', sa.VARCHAR(length=256),
                              autoincrement=False, nullable=True),
                    sa.Column('auth_srid', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('srtext', sa.VARCHAR(length=2048),
                              autoincrement=False, nullable=True),
                    sa.Column('proj4text', sa.VARCHAR(length=2048),
                              autoincrement=False, nullable=True),
                    sa.CheckConstraint('srid > 0 AND srid <= 998999',
                                       name=op.f('spatial_ref_sys_srid_check')),
                    sa.PrimaryKeyConstraint(
                        'srid', name=op.f('spatial_ref_sys_pkey'))
                    )
    op.drop_table('scans')
    # ### end Alembic commands ###
